import React, { useState } from "react";
import { 
  CupSoda, 
  HelpCircle, 
  Users, 
  Sparkles, 
  Mail, 
  MapPin, 
  Languages, 
  Send, 
  RotateCw,
  Clock,
  Briefcase,
  Play,
  Volume2
} from "lucide-react";

interface CoffeeRouletteProps {
  coffeeMatches: any[];
  onTriggerJoinPool: (office: string) => Promise<any>;
  onAddLog: (level: "info" | "success" | "warn" | "error", message: string) => void;
}

export default function CoffeeRoulette({ coffeeMatches, onTriggerJoinPool, onAddLog }: CoffeeRouletteProps) {
  const [selectedOffice, setSelectedOffice] = useState("malta");
  
  // Roulette search state
  const [isSearching, setIsSearching] = useState(false);
  const [matchedPayload, setMatchedPayload] = useState<any | null>(null);

  // Gemini translator / Coach states
  const [englishText, setEnglishText] = useState("Let's go have some food and coffee!");
  const [coachTargetOffice, setCoachTargetOffice] = useState("cyberjaya");
  const [coachResponse, setCoachResponse] = useState<any | null>(null);
  const [translating, setTranslating] = useState(false);

  // Gemini icebreaker generator states
  const [generatingIce, setGeneratingIce] = useState(false);
  const [icebreakerResult, setIcebreakerResult] = useState<any | null>(null);

  const officesDetailsMap: { [key: string]: { city: string; country: string } } = {
    cyberjaya: { city: "Cyberjaya", country: "Malaysia" },
    malta: { city: "Mosta", country: "Malta" },
    kigali: { city: "Kigali", country: "Rwanda" },
    dubai: { city: "Dubai", country: "UAE" },
    limassol: { city: "Limassol", country: "Cyprus" },
    asuncion: { city: "Asunción", country: "Paraguay" }
  };

  const currentMatch = matchedPayload || (coffeeMatches.length > 0 ? coffeeMatches[0] : null);

  const handleJoinRoulette = async () => {
    setIsSearching(true);
    setMatchedPayload(null);
    setIcebreakerResult(null);
    onAddLog("info", `Searching the global Deriv watercooler pool for an available Coffee Roulette peer match...`);

    // Simulate standard slot-spin delay
    setTimeout(async () => {
      try {
        const match = await onTriggerJoinPool(selectedOffice);
        setMatchedPayload(match);
        onAddLog("success", `Match found! Connected user with ${match.matchedName} from ${match.matchedOffice}.`);
      } catch (err: any) {
        onAddLog("error", `Failed finding match: ${err.message}`);
      } finally {
        setIsSearching(false);
      }
    }, 2200);
  };

  const handleLocalizePhrase = async () => {
    if (!englishText.trim()) return;
    setTranslating(true);
    onAddLog("info", `Calling Gemini AI Coach to localize phrase: "${englishText}" for ${coachTargetOffice.toUpperCase()}...`);

    const coords = officesDetailsMap[coachTargetOffice] || { city: "Unknown", country: "Unknown" };

    try {
      const response = await fetch("/api/ai/coach", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          phrase: englishText,
          targetOffice: coachTargetOffice,
          targetCity: coords.city,
          targetCountry: coords.country
        })
      });

      if (response.ok) {
        const data = await response.json();
        setCoachResponse(data);
        onAddLog("success", `Gemini response loaded: Localized translation created!`);
      } else {
        onAddLog("error", `Cognitive translation route returned status error.`);
      }
    } catch (err: any) {
      onAddLog("error", `AI Coach request failed: ${err.message}`);
    } finally {
      setTranslating(false);
    }
  };

  const handleGenerateIcebreaker = async () => {
    if (!currentMatch) return;
    setGeneratingIce(true);
    onAddLog("info", `Gemini generating inter-office social mixer activity...`);

    try {
      const response = await fetch("/api/ai/generate-icebreaker", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          officeA: selectedOffice.toUpperCase() + " office",
          officeB: currentMatch.matchedOffice
        })
      });

      if (response.ok) {
        const data = await response.json();
        setIcebreakerResult(data);
        onAddLog("success", `Dual cultural virtual mixer prompt generated by Gemini successfully.`);
      } else {
        onAddLog("error", `Failed requesting icebreaker API.`);
      }
    } catch (err: any) {
      onAddLog("error", `Icebreaker error: ${err.message}`);
    } finally {
      setGeneratingIce(false);
    }
  };

  return (
    <div id="roulette_view_container" className="grid grid-cols-1 md:grid-cols-12 gap-6 animate-fade-in">
      
      {/* LEFT COLUMN: Coffee Roulette Interactive Matchmaker */}
      <div className="md:col-span-6 space-y-6">
        <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-xs flex flex-col justify-between min-h-[420px]">
          <div>
            <h3 className="font-extrabold text-slate-900 text-sm tracking-tight flex items-center gap-2 border-b border-slate-100 pb-3 mb-4">
              <CupSoda className="text-deriv-red animate-bounce" size={18} />
              <span>Coffee Roulette Hub</span>
            </h3>

            <p className="text-xs text-slate-500 leading-relaxed mb-4">
              Cross-office collaboration sparks incredible ideas! Select your physical desk office location, spin the roulette wheel, and match with a colleague across the globe for a quick virtual coffee break.
            </p>

            <div className="grid grid-cols-1 gap-3.5 bg-slate-50/75 border border-slate-200/50 rounded-xl p-4 mb-5 text-xs font-semibold text-slate-700">
              <div>
                <label className="block text-[9px] font-extrabold text-deriv-red uppercase tracking-wider mb-1">Your location</label>
                <select
                  value={selectedOffice}
                  onChange={(e) => setSelectedOffice(e.target.value)}
                  className="bg-white border border-slate-200 rounded-lg p-2.5 w-full font-bold focus:border-deriv-red focus:ring-1 focus:ring-deriv-red/20 focus:outline-hidden cursor-pointer transition"
                >
                  <option value="malta">Malta Office (Mosta)</option>
                  <option value="cyberjaya">Malaysia Office (Cyberjaya)</option>
                  <option value="kigali">Rwanda Office (Kigali)</option>
                  <option value="dubai">Dubai Office (UAE)</option>
                  <option value="limassol">Cyprus Office (Limassol)</option>
                  <option value="asuncion">Paraguay Office (Asunción)</option>
                </select>
              </div>

              <button
                type="button"
                onClick={handleJoinRoulette}
                disabled={isSearching}
                className="w-full inline-flex items-center justify-center gap-1.5 px-4 py-2.5 bg-deriv-red hover:bg-deriv-red-hover disabled:bg-rose-300 text-white font-extrabold uppercase tracking-wider rounded-xl transition duration-150 active:scale-95 cursor-pointer shadow-md shadow-deriv-red/10"
              >
                {isSearching ? (
                  <>
                    <RotateCw className="animate-spin text-white" size={13} />
                    <span>Spinning Roulette Wheel...</span>
                  </>
                ) : (
                  <>
                    <Play size={12} className="fill-current text-white cursor-pointer" />
                    <span>Join Coffee Roulette Match pool</span>
                  </>
                )}
              </button>
            </div>
          </div>

          {/* SPINNING ANIMATION OR MATCH CARD RESULT */}
          <div className="min-h-[140px] flex items-center justify-center border-t border-slate-100/80 pt-4">
            {isSearching ? (
              <div className="text-center space-y-2 animate-pulse">
                <div className="relative inline-flex items-center justify-center">
                  <div className="w-12 h-12 rounded-full border-4 border-rose-100 border-t-deriv-red animate-spin"></div>
                  <Users className="text-deriv-red absolute shrink-0" size={16} />
                </div>
                <div className="text-[10px] font-extrabold text-deriv-red uppercase tracking-widest animate-pulse">Scanning peer schedules...</div>
              </div>
            ) : currentMatch ? (
              <div className="w-full bg-slate-50 border border-slate-200/50 rounded-xl p-4 space-y-3 shadow-inner">
                <div className="text-slate-400 text-[10px] uppercase font-extrabold tracking-wider flex items-center justify-between">
                  <span>Match Established!</span>
                  <span className="font-mono text-deriv-red text-[9px] bg-rose-50 px-2.5 py-0.5 border border-rose-200 rounded-md">Connected</span>
                </div>

                <div className="flex items-start gap-3">
                  <div className={`w-10 h-10 rounded-xl flex items-center justify-center text-white font-extrabold shrink-0 text-sm shadow-xs bg-deriv-red`}>
                    {currentMatch.matchedName.split(' ')[0][0]}{currentMatch.matchedName.split(' ').slice(-1)[0][0]}
                  </div>
                  <div>
                    <h4 className="font-bold text-slate-800 text-xs">{currentMatch.matchedName}</h4>
                    
                    <div className="space-y-1 mt-1 text-[11px] text-slate-500">
                      <div className="flex items-center gap-1">
                        <Briefcase size={10} className="text-slate-400" />
                        <span>{currentMatch.matchedRole}</span>
                      </div>
                      <div className="flex items-center gap-1 font-bold text-slate-700">
                        <MapPin size={10} className="text-deriv-red" />
                        <span>{currentMatch.matchedOffice}</span>
                      </div>
                      <div className="flex items-center gap-1 font-mono text-[10px] text-deriv-red-hover">
                        <Mail size={10} className="text-slate-400" />
                        <span className="select-all">{currentMatch.matchedEmail}</span>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Trigger icebreaker generation */}
                <div className="pt-2 border-t border-slate-200/50 flex justify-end">
                  <button
                    type="button"
                    onClick={handleGenerateIcebreaker}
                    disabled={generatingIce}
                    className="inline-flex items-center gap-1 px-3 py-1.5 bg-rose-50 hover:bg-rose-100 border border-rose-200 text-deriv-red rounded-lg text-[10px] font-black uppercase transition active:scale-95 shadow-2xs cursor-pointer"
                  >
                    <Sparkles size={10} className="text-deriv-red" />
                    <span>{generatingIce ? "Thinking of Game..." : "Generate AI Mixer Game"}</span>
                  </button>
                </div>
              </div>
            ) : (
              <div className="text-center text-slate-400 max-w-xs space-y-1.5 py-4">
                <Users className="mx-auto text-slate-300" size={32} />
                <h4 className="text-xs font-bold text-slate-600">No active coffee pair match selected</h4>
                <p className="text-[10px] leading-relaxed">
                  Join the pool above to find peer matches across Limassol, Cyberjaya, Malta, and Kigali.
                </p>
              </div>
            )}
          </div>
        </div>

        {/* Gemini Generated social Mixer Icebreaker prompt */}
        {icebreakerResult && (
          <div className="bg-slate-900 border border-slate-800 text-slate-100 rounded-2xl p-5 space-y-2.5 shadow-md">
            <h4 className="text-[10px] font-extrabold text-deriv-red uppercase tracking-widest flex items-center gap-1.5">
              <Sparkles size={12} className="text-deriv-red shrink-0" />
              <span>AI Inter-Office Mixer Activity</span>
            </h4>
            <div className="font-extrabold text-white text-sm tracking-tight border-b border-white/5 pb-2">
              {icebreakerResult.title}
            </div>
            <p className="text-xs text-slate-300 leading-relaxed font-sans font-medium">
              {icebreakerResult.activity}
            </p>
          </div>
        )}
      </div>

      {/* RIGHT COLUMN: AI SLANG COACH / CULTURAL RESEARCH DIALECT TOOL */}
      <div className="md:col-span-6 space-y-4">
        <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-xs space-y-4">
          <h3 className="font-extrabold text-slate-900 text-sm tracking-tight flex items-center gap-2 border-b border-slate-100 pb-3">
            <Languages className="text-deriv-red shrink-0" size={18} />
            <span>AI Slang Coach & translator</span>
          </h3>

          <p className="text-xs text-slate-500 leading-relaxed">
            Translate conversational phrases into country-specific expressions used by actual regional offices. Excellent for starting chats on Slack or during video meetings. No trading metrics, purely human social connections!
          </p>

          <div className="space-y-3.5 text-xs font-bold text-slate-700">
            <div>
              <label className="block text-[9px] font-extrabold text-slate-400 uppercase tracking-wider mb-1">Enter Conversational English Phrase</label>
              <textarea
                rows={2}
                value={englishText}
                onChange={(e) => setEnglishText(e.target.value)}
                placeholder="Type anything, e.g. Good morning, want to do coffee?"
                className="w-full bg-slate-50 border border-slate-200 focus:border-deriv-red focus:ring-1 focus:ring-deriv-red/20 rounded-lg p-2.5 font-medium font-sans focus:outline-hidden transition"
              />
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="block text-[9px] font-extrabold text-slate-400 uppercase tracking-wider mb-1">Target Office culture</label>
                <select
                  value={coachTargetOffice}
                  onChange={(e) => setCoachTargetOffice(e.target.value)}
                  className="bg-slate-50 border border-slate-200 rounded-lg p-2 w-full font-bold focus:border-deriv-red focus:ring-1 focus:ring-deriv-red/20 focus:outline-hidden cursor-pointer transition"
                >
                  <option value="cyberjaya">Malaysia (Cyberjaya)</option>
                  <option value="malta">Malta (Mosta/Valletta)</option>
                  <option value="kigali">Rwanda (Kigali)</option>
                  <option value="dubai">Dubai (UAE)</option>
                  <option value="limassol">Cyprus (Limassol)</option>
                  <option value="asuncion">Paraguay (Asunción)</option>
                </select>
              </div>

              <div className="flex items-end">
                <button
                  type="button"
                  onClick={handleLocalizePhrase}
                  disabled={translating || !englishText.trim()}
                  className="w-full inline-flex items-center justify-center gap-1 px-4 py-2 bg-deriv-red hover:bg-deriv-red-hover disabled:bg-rose-300 text-white font-extrabold uppercase tracking-wider rounded-xl transition duration-150 active:scale-95 shadow-md shadow-deriv-red/10 cursor-pointer text-[10px]"
                >
                  <Sparkles size={11} className="text-white hover:scale-110 transition shrink-0" />
                  <span>{translating ? "Translating..." : "Localize with AI"}</span>
                </button>
              </div>
            </div>
          </div>

          {/* AI Result Card */}
          {coachResponse && (
            <div className="bg-slate-50 border border-slate-200 rounded-xl p-4 space-y-3 shadow-inner">
              <div className="text-slate-400 text-[9px] uppercase font-extrabold tracking-wider">
                Gemini localized slang suggestion
              </div>

              <div className="flex items-start justify-between border-b border-slate-200/50 pb-2">
                <div>
                  <div className="text-deriv-red font-black text-sm font-mono flex items-center gap-1 bg-white border border-slate-200 w-fit px-2.5 py-0.5 rounded shadow-2xs">
                    "{coachResponse.translation}"
                  </div>
                  <div className="text-[10px] text-slate-400 font-mono italic mt-1 flex items-center gap-1">
                    <Volume2 size={10} className="text-slate-400 shrink-0" />
                    <span>Pronounced: {coachResponse.pronunciation}</span>
                  </div>
                </div>
              </div>

              <div>
                <div className="text-[9px] font-extrabold text-slate-400 uppercase mb-0.5">Lifestyle context note</div>
                <p className="text-slate-600 text-xs font-semibold font-sans leading-relaxed text-slate-700">
                  {coachResponse.culturalTip}
                </p>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
